services:
  db:
    image: mysql:8
    restart: always
    volumes:
      - /home/zhengtianbao/mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    expose:
      - 3306
  backend:
    image: json_exporter:0.0.1-SNAPSHOT
    expose:
      - 8080
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/backend
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/prometheus?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - db
  frontend:
    image: json_exporter_frontend:latest
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - backend
